### PR TITLE
Fixes to comply with the new changes to the API

### PR DESCRIPTION
**Pull request by RealGatt**

### CODE REVIEW

**Comment by nikolaspikolas** [comment]
Not a fan of the `matchesUserID` and `matchesUserName` methods. They aren't really relevant in the scope of this project.

**Comment by nikolaspikolas** [comment]
Also -- the `hasVoted()` method means that it would be used as `hasVoted(...).hasVoted()` which seems really redundant. This does bring up a larger issue -- perhaps it's time to move away from Retrofit and get closer to the raw http requests.

**Comment by nikolaspikolas** [comment]
I've decided to rewrite the library from scratch (mostly) instead of merging this.

**Comment by RealGatt** [comment]
No worries. My changes were mostly for personal use, ie; `matchesUserID()`. It was a bandaid fix and a learning opportunity for me to learn RetroFit.

Thanks for picking it back up.

**Pull request closed without merging**
